job-service.url=http://job:8082
company-service.url=http://company:8081
review-service.url=http://review:8083

spring.application.name=companyms
server.port=8081
# spring.h2.console.enabled = true
# spring.datasource.url = jdbc:h2:mem:test
# spring.jpa.generate-ddl = true
# spring.jpa.show-sql = true
#postgres
spring.datasource.url=jdbc:postgresql://postgres:5432/companyms
spring.datasource.username=postgres
spring.datasource.password=hdemus
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://servicereg:8761/eureka/
#config-server
spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://config-server:8080}

#rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest