job-service.url=http://job
company-service.url=http://company
review-service.url=http://review

spring.application.name=companyms
server.port=8081
# spring.h2.console.enabled = true
# spring.datasource.url = jdbc:h2:mem:test
# spring.jpa.generate-ddl = true
# spring.jpa.show-sql = true
#postgres
spring.datasource.url=jdbc:postgresql://postgres:5432/companyms
spring.datasource.username=postgres
spring.datasource.password=hdemus
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#eureka
eureka.client.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
# eureka.client.service-url.defaultZone=http://servicereg:8761/eureka/
#config-server
# spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://config-server:8080}
logging.level.debug=DEBUG
#rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

#actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=false